---
- name: Install Nginx Web Server
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Ensure Nginx Service is Running
  service:
    name: nginx
    state: started
    enabled: yes

- name: Deploy Dynamic index.html Page
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: Reload Nginx Service
